# Generated by Django 3.0.4 on 2021-12-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_cursos_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
